server:
  port: 8093
spring:
  redis:
    database: 0
    host: 127.0.01
    password: ''
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379

logging:
  level:
    com.example.zzyymaggie: debug
