// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.example.zzyymaggie.protocol.task;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class FeedbackPrxCallback extends TarsAbstractCallback {

	public abstract void callback_feedback(int ret, String msg);

}
